name: gatekeeper_plugin
version: '${project.version}'
main: dev.atelierlune.jiansu.gatekeeper_plugin.Gatekeeper_plugin
api-version: 1.19
authors: [Jiansu (sanamorii)]
description: Minecraft whitelisting bot for discord.
website: sanamorii.github.io
